name: knx_parse_example
description: Web app to parse KNX .knxproj files to JSON using knx_parse.
version: 1.0.0
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  knx_parser: ^1.4.0

dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.0
